sudo: required
services:
  - docker
  
before_install:
   - docker build  -t ninja/docker-react -f Dockerfile.dev . 
   
script:
  - docker run -e CI=true ninja/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucker_name: "elasticbeanstalk-ap-south-1-566334774032"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure:"$AWS_SECRET_KEY"  